language: java
cache:
  directories:
  - "$HOME/.gradle/caches/2.11"
  - "$HOME/.gradle/caches/jars-1"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/wrapper"
# Append git tag to the compiled jar
# https://github.com/GTNewHorizons/TinkersConstruct/blob/1.7.10/build.gradle#L103
before_install:
- export ARTIFACT_VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: he2rOPBXPGTTDimG/qwKkZtbX5K+utGL13wjhQtHcAPXrVgiJYdAyM+LpJGBH3pwU/pertX1jj+pvAaWpPB9IcO+GT2MyM5mWjIut0aIN+dXdT7trsX8LcJ8LLtPrVDmzPKioPPuP0akr5G+NV2clO3zGdHSPUxthZZLI4+4KILMJSApnhItkUJFnIZmJpjrkScZwZcUgb5KR3v/7l2axmwQKsGBPb/mdgQUymgfLOoPzPLSVx+e768no0dvq7swQw06LVauFB0WIb3rUq5sr1tMPRyOx1WVjy7ERixc8UVlquPE7IZBAlyeyHETTImsxd8xCbSvtezvsBWOhhQ13ADFpHNxHRPPd3Akd+4y+NpedGj9g1XBI5tLNhIcmhwtIYQBCQarDEF4U7iNruMSgjeZ3LAjWj+o4BUdKtA+Yz44ByA3lbLqVXjL4bQJseLju4jINY0uX2j4Eb2mDDeEGKirxu4ZFGwLoGLHh5ZDAKP9BWmGM/9ksJ0BFlafFX2BkIDivyiFfzWB4uLv/n2bZOTOodK1SJr5RVPVvirepqn+1wm3pmGTQ/0DLjOiqFyDncWwCc1aBQXo91FHDEaA42j01/r5mnAE7WkCTp2/Hq44VFvAUBpXBVwIWZBN6QhlBJf2DPXVmFWqCAUz77nG4YD/6YdEyNR8vBerFxLMm6E=
  file: build/libs/TConstruct-1.7.10-*-GTNH.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: GTNewHorizons/TinkersConstruct
    tags: true
