language: python
sudo: false
notifications:
  email: false
  irc:
    channels:
      secure: Rd4c9WhmrVR6PnvUlJG98iTwwPI7AskIfdfSmjiM5A2RlU1kMLhe8MzZsrDniJlWvG5FVJVnWKw5j2tLQXwwLfUj5LngVj3XKp62fuV7QT9RhfTSZ7piKWUtNHZz+zcujBf/AgONsHjMEJQ4/LDIwiQncPtaf8uDj9VEolvvUgJEuoy9gl+cARVqaD3C6v8/ZhoxcBsDfBDS0G+UBqDMzq/XuFnyQA5ztorXgryLFPpW2nHDjKlyNy/9SVx65Q84C+eblxovTf/PtAtZTPGEbEuc3Xuxbt+Oxcu1VPK4lVit3lgPxK8LeW4E9/naafjpjmUlVPaEdlWrqnYqY41HQShhyA0daTP6eBp8atPViyTVpo7+Vr2FoPWBulkJMHiP0TajBZSN++3D0EGCrzEKAyucYR2cetknkwIU35C19WqtaVFXQIZeeDyLDYdkAHXfacZ+cJLox1XoBxkbkmXXAu9WUEPLDptGv+7Po1ZiuVeybWeJD9B/a22hrDzYr2fsv5Z3XROapN670pHduNLqNBJl40Pob3+hZ5EHbRxrUWmJBFvewYZuSlatFWc/DHdT9pbph0b3LA/ImYE55K+o/Q3iVsPtXWvSKFkXz/E/o5F4x4NZGAVrwwT1UW1a9xdCvv+mAMoSTHHoknjDwgRjjODyEhV4tVUi4LMppMGF+0E=
    nick: travis-ci
    password:
      secure: wKlUtsVuZb478agCE0DzN8DnSgT63o3Kiw6YHSwF1WueMQY5FqD8nIn4+7tHG5UnU3eI/Kfqjoq17sG6JRGnEGz3ks2ln19//MdMcZeOlknzKE/903p7UTXbYuvHSn9blrxrV0oskbg4xmTiQPe1sn4pMug3y5ozxZSNspqzrIT34hEqio9+1JDCDHp6Bb+yukxsYHpuTQtMBdCY+6PQFUPAKF7AczLevL/4UIYVNHGDB96Vtfelxw9ZPxTKTFPZ5V5hH8/zR9QjOQUUZDQk/D8x+j14VHAZosuYjjgrv9EKD/vdfW3vIhJynWkO+Mvuj6u7nrUaLOugEbKMo+YnizGcRiMJlD95pP+V69jKUl7zXyG9mo0xLSp8EOaN5qhhlCHbnt0WPtcg/mogxZrrTQHYmslWebpcs7GCFk8EE0UbLgKOUZq/1SroCL2e6y9kkihcfqYaktzTWUsJPn1V0RnJnSLakYRKU1J4cjoxjR0njVa9z9JVPFpRgh8pVHFZh/I0Ee57dWtJqJoseiobJqsCi5al4dg4dH4fVELMWntOJJRRWydbbr0KzBHDOyynXRUpAZlkYp4Kab5mfi5wD6cLgqePlaVYDy2YL7SCI5osTh8oCgsKkq7EDEVb42hgLwm/xKqbVqCxs7pM5Wi8A2aLDgIpd1SjoiUHKYo614A=
install:
- pip install codecov
script:
- codecov run tests.py
after_success:
- codecov